---
- name: Install the required things
  hosts: all
  collections:
    - name: 'it_pappa.win_print'
      version: '1.0.0'
    
  tasks:
    - name: "Install Printer port"
      add_print_port:
        port_address: "10.54.10.100"
        port_name: CEO_Printer
        snmp: public3
        state: present
